group=player-data

[file]
filename=Shinobi/Idle.png
alias=player_idle.png

[file]
filename=Shinobi/Attack_1.png
alias=player_attack.png

[file]
filename=Shinobi/Run.png
alias=player_run.png

[file]
filename=Shinobi/Walk.png
alias=player_walk.png
